/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author javie
 */
public class Mapa extends javax.swing.JFrame {

    /**
     * Creates new form Mapa
     */
    public Mapa() {
        initComponents();
        this.setTitle("Mapa");
        this.setResizable(false);
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/2.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P24 = new javax.swing.JLabel();
        P23 = new javax.swing.JLabel();
        P22 = new javax.swing.JLabel();
        P21 = new javax.swing.JLabel();
        P20 = new javax.swing.JLabel();
        P19 = new javax.swing.JLabel();
        P18 = new javax.swing.JLabel();
        P17 = new javax.swing.JLabel();
        P16 = new javax.swing.JLabel();
        P15 = new javax.swing.JLabel();
        P14 = new javax.swing.JLabel();
        P12 = new javax.swing.JLabel();
        P13 = new javax.swing.JLabel();
        P11 = new javax.swing.JLabel();
        P10 = new javax.swing.JLabel();
        P9 = new javax.swing.JLabel();
        P8 = new javax.swing.JLabel();
        P7 = new javax.swing.JLabel();
        P6 = new javax.swing.JLabel();
        P5 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        B26 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B9 = new javax.swing.JLabel();
        B10 = new javax.swing.JLabel();
        B8 = new javax.swing.JLabel();
        B11 = new javax.swing.JLabel();
        B13 = new javax.swing.JLabel();
        B12 = new javax.swing.JLabel();
        B14 = new javax.swing.JLabel();
        B15 = new javax.swing.JLabel();
        B17 = new javax.swing.JLabel();
        B18 = new javax.swing.JLabel();
        B16 = new javax.swing.JLabel();
        B19 = new javax.swing.JLabel();
        B20 = new javax.swing.JLabel();
        B21 = new javax.swing.JLabel();
        B23 = new javax.swing.JLabel();
        B22 = new javax.swing.JLabel();
        B24 = new javax.swing.JLabel();
        B25 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        E2 = new javax.swing.JLabel();
        E3 = new javax.swing.JLabel();
        E4 = new javax.swing.JLabel();
        E5 = new javax.swing.JLabel();
        Ey = new javax.swing.JLabel();
        T1 = new javax.swing.JLabel();
        T2 = new javax.swing.JLabel();
        T3 = new javax.swing.JLabel();
        T4 = new javax.swing.JLabel();
        T5 = new javax.swing.JLabel();
        T6 = new javax.swing.JLabel();
        T7 = new javax.swing.JLabel();
        T8 = new javax.swing.JLabel();
        Ty = new javax.swing.JLabel();
        H1 = new javax.swing.JLabel();
        H2 = new javax.swing.JLabel();
        H3 = new javax.swing.JLabel();
        H4 = new javax.swing.JLabel();
        H5 = new javax.swing.JLabel();
        H6 = new javax.swing.JLabel();
        H7 = new javax.swing.JLabel();
        Hy = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        C7 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        C9 = new javax.swing.JLabel();
        Cy = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        D8 = new javax.swing.JLabel();
        D9 = new javax.swing.JLabel();
        D10 = new javax.swing.JLabel();
        D11 = new javax.swing.JLabel();
        D12 = new javax.swing.JLabel();
        D13 = new javax.swing.JLabel();
        D14 = new javax.swing.JLabel();
        D15 = new javax.swing.JLabel();
        D16 = new javax.swing.JLabel();
        D17 = new javax.swing.JLabel();
        D18 = new javax.swing.JLabel();
        D19 = new javax.swing.JLabel();
        D20 = new javax.swing.JLabel();
        D21 = new javax.swing.JLabel();
        D22 = new javax.swing.JLabel();
        Dy = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        A9 = new javax.swing.JLabel();
        A10 = new javax.swing.JLabel();
        A11 = new javax.swing.JLabel();
        A12 = new javax.swing.JLabel();
        Ay = new javax.swing.JLabel();
        Mapa_Superior = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P24MouseClicked(evt);
            }
        });
        getContentPane().add(P24, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, -1, 20));

        P23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P23MouseClicked(evt);
            }
        });
        getContentPane().add(P23, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, -1, 20));

        P22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P22MouseClicked(evt);
            }
        });
        getContentPane().add(P22, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, -1, 20));

        P21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P21MouseClicked(evt);
            }
        });
        getContentPane().add(P21, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, -1, 20));

        P20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P20MouseClicked(evt);
            }
        });
        getContentPane().add(P20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, -1, 20));

        P19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P19MouseClicked(evt);
            }
        });
        getContentPane().add(P19, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, -1, 20));

        P18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P18MouseClicked(evt);
            }
        });
        getContentPane().add(P18, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 360, -1, 20));

        P17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P17MouseClicked(evt);
            }
        });
        getContentPane().add(P17, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, -1, 20));

        P16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P16MouseClicked(evt);
            }
        });
        getContentPane().add(P16, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, -1, 20));

        P15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P15MouseClicked(evt);
            }
        });
        getContentPane().add(P15, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, -1, 20));

        P14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P14MouseClicked(evt);
            }
        });
        getContentPane().add(P14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, -1, 20));

        P12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P12MouseClicked(evt);
            }
        });
        getContentPane().add(P12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, 20));

        P13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P13MouseClicked(evt);
            }
        });
        getContentPane().add(P13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, -1, 20));

        P11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P11MouseClicked(evt);
            }
        });
        getContentPane().add(P11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, 20));

        P10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P10MouseClicked(evt);
            }
        });
        getContentPane().add(P10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, 20));

        P9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P9MouseClicked(evt);
            }
        });
        getContentPane().add(P9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, 20));

        P8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P8MouseClicked(evt);
            }
        });
        getContentPane().add(P8, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 476, -1, 20));

        P7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P7MouseClicked(evt);
            }
        });
        getContentPane().add(P7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, -1, 20));

        P6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P6MouseClicked(evt);
            }
        });
        getContentPane().add(P6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 530, -1, 20));

        P5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P5MouseClicked(evt);
            }
        });
        getContentPane().add(P5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, -1, 20));

        P4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P4MouseClicked(evt);
            }
        });
        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 430, -1, 20));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, 20));

        P3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P3MouseClicked(evt);
            }
        });
        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 390, -1, 20));

        P2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P2MouseClicked(evt);
            }
        });
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, -1, 20));

        B26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_food.png"))); // NOI18N
        B26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B26MouseClicked(evt);
            }
        });
        getContentPane().add(B26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        P1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        P1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1MouseClicked(evt);
            }
        });
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_food.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 470, -1, -1));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, 20));

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, 20));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, 20));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, 20));

        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });
        getContentPane().add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, 20));

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });
        getContentPane().add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, 20));

        B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B9MouseClicked(evt);
            }
        });
        getContentPane().add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, 20));

        B10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B10MouseClicked(evt);
            }
        });
        getContentPane().add(B10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, 20));

        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });
        getContentPane().add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, 20));

        B11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B11MouseClicked(evt);
            }
        });
        getContentPane().add(B11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, 20));

        B13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B13MouseClicked(evt);
            }
        });
        getContentPane().add(B13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, 20));

        B12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B12MouseClicked(evt);
            }
        });
        getContentPane().add(B12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, 20));

        B14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B14MouseClicked(evt);
            }
        });
        getContentPane().add(B14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, 20));

        B15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B15MouseClicked(evt);
            }
        });
        getContentPane().add(B15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, 20));

        B17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B17MouseClicked(evt);
            }
        });
        getContentPane().add(B17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, 20));

        B18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B18MouseClicked(evt);
            }
        });
        getContentPane().add(B18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, 20));

        B16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B16MouseClicked(evt);
            }
        });
        getContentPane().add(B16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, 20));

        B19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B19MouseClicked(evt);
            }
        });
        getContentPane().add(B19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, 20));

        B20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B20MouseClicked(evt);
            }
        });
        getContentPane().add(B20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, 20));

        B21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B21MouseClicked(evt);
            }
        });
        getContentPane().add(B21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, 20));

        B23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B23MouseClicked(evt);
            }
        });
        getContentPane().add(B23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, 20));

        B22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B22MouseClicked(evt);
            }
        });
        getContentPane().add(B22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, 20));

        B24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B24MouseClicked(evt);
            }
        });
        getContentPane().add(B24, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, 20));

        B25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        B25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B25MouseClicked(evt);
            }
        });
        getContentPane().add(B25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, 20));

        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E1MouseClicked(evt);
            }
        });
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, -1, 20));

        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        E2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2MouseClicked(evt);
            }
        });
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, -1, 20));

        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        E3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E3MouseClicked(evt);
            }
        });
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 560, -1, 20));

        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        E4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E4MouseClicked(evt);
            }
        });
        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, -1, 20));

        E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        E5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E5MouseClicked(evt);
            }
        });
        getContentPane().add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 530, -1, 20));

        Ey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_food.png"))); // NOI18N
        Ey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EyMouseClicked(evt);
            }
        });
        getContentPane().add(Ey, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 30, 30));

        T1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        T1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T1MouseClicked(evt);
            }
        });
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, 20));

        T2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        T2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T2MouseClicked(evt);
            }
        });
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, -1, 20));

        T3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        T3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3MouseClicked(evt);
            }
        });
        getContentPane().add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, -1, 20));

        T4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        T4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4MouseClicked(evt);
            }
        });
        getContentPane().add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, -1, 20));

        T5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        T5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5MouseClicked(evt);
            }
        });
        getContentPane().add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, -1, 20));

        T6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        T6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T6MouseClicked(evt);
            }
        });
        getContentPane().add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, -1, 20));

        T7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        T7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T7MouseClicked(evt);
            }
        });
        getContentPane().add(T7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, -1, 20));

        T8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        T8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T8MouseClicked(evt);
            }
        });
        getContentPane().add(T8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, -1, 20));

        Ty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_food.png"))); // NOI18N
        Ty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TyMouseClicked(evt);
            }
        });
        getContentPane().add(Ty, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 690, 30, 30));

        H1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        H1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H1MouseClicked(evt);
            }
        });
        getContentPane().add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, -1, 20));

        H2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        H2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H2MouseClicked(evt);
            }
        });
        getContentPane().add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, 20));

        H3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        H3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H3MouseClicked(evt);
            }
        });
        getContentPane().add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, 20));

        H4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        H4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H4MouseClicked(evt);
            }
        });
        getContentPane().add(H4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, 20));

        H5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        H5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H5MouseClicked(evt);
            }
        });
        getContentPane().add(H5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, 20));

        H6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        H6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H6MouseClicked(evt);
            }
        });
        getContentPane().add(H6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, 20));

        H7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        H7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H7MouseClicked(evt);
            }
        });
        getContentPane().add(H7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, 20));

        Hy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_food.png"))); // NOI18N
        Hy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HyMouseClicked(evt);
            }
        });
        getContentPane().add(Hy, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 30, 30));

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C1MouseClicked(evt);
            }
        });
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, 20));

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C2MouseClicked(evt);
            }
        });
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, 20));

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C3MouseClicked(evt);
            }
        });
        getContentPane().add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, 20));

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        C4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C4MouseClicked(evt);
            }
        });
        getContentPane().add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, 20));

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        C5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C5MouseClicked(evt);
            }
        });
        getContentPane().add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, 20));

        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        C6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C6MouseClicked(evt);
            }
        });
        getContentPane().add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, 20));

        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        C7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C7MouseClicked(evt);
            }
        });
        getContentPane().add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, 20));

        C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        C8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C8MouseClicked(evt);
            }
        });
        getContentPane().add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, 20));

        C9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        C9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C9MouseClicked(evt);
            }
        });
        getContentPane().add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, 20));

        Cy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_food.png"))); // NOI18N
        Cy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CyMouseClicked(evt);
            }
        });
        getContentPane().add(Cy, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 30, 30));

        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D1MouseClicked(evt);
            }
        });
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D2MouseClicked(evt);
            }
        });
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 20));

        D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D3MouseClicked(evt);
            }
        });
        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, 20));

        D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D4MouseClicked(evt);
            }
        });
        getContentPane().add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, 20));

        D5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D5MouseClicked(evt);
            }
        });
        getContentPane().add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, 20));

        D6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D6MouseClicked(evt);
            }
        });
        getContentPane().add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 20));

        D7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D7MouseClicked(evt);
            }
        });
        getContentPane().add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, 20));

        D8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D8MouseClicked(evt);
            }
        });
        getContentPane().add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, 20));

        D9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D9MouseClicked(evt);
            }
        });
        getContentPane().add(D9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 20));

        D10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D10MouseClicked(evt);
            }
        });
        getContentPane().add(D10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, 20));

        D11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D11MouseClicked(evt);
            }
        });
        getContentPane().add(D11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, 20));

        D12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D12MouseClicked(evt);
            }
        });
        getContentPane().add(D12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, 20));

        D13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D13MouseClicked(evt);
            }
        });
        getContentPane().add(D13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, 20));

        D14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D14MouseClicked(evt);
            }
        });
        getContentPane().add(D14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, 20));

        D15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D15MouseClicked(evt);
            }
        });
        getContentPane().add(D15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, 20));

        D16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D16MouseClicked(evt);
            }
        });
        getContentPane().add(D16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, 20));

        D17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D17MouseClicked(evt);
            }
        });
        getContentPane().add(D17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, 20));

        D18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D18MouseClicked(evt);
            }
        });
        getContentPane().add(D18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, 20));

        D19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D19MouseClicked(evt);
            }
        });
        getContentPane().add(D19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, 20));

        D20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D20MouseClicked(evt);
            }
        });
        getContentPane().add(D20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 20));

        D21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D21MouseClicked(evt);
            }
        });
        getContentPane().add(D21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 20));

        D22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        D22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D22MouseClicked(evt);
            }
        });
        getContentPane().add(D22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, 20));

        Dy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_food.png"))); // NOI18N
        Dy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DyMouseClicked(evt);
            }
        });
        getContentPane().add(Dy, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 30, 30));

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 20));

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });
        getContentPane().add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, 20));

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
        });
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, 20));

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A4MouseClicked(evt);
            }
        });
        getContentPane().add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 20));

        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A5MouseClicked(evt);
            }
        });
        getContentPane().add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, 20));

        A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A6MouseClicked(evt);
            }
        });
        getContentPane().add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 20));

        A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A7MouseClicked(evt);
            }
        });
        getContentPane().add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 20));

        A8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A8MouseClicked(evt);
            }
        });
        getContentPane().add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, 20));

        A9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A9MouseClicked(evt);
            }
        });
        getContentPane().add(A9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 20));

        A10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A10MouseClicked(evt);
            }
        });
        getContentPane().add(A10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, 20));

        A11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A11MouseClicked(evt);
            }
        });
        getContentPane().add(A11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 20));

        A12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_location_on_black_18dp.png"))); // NOI18N
        A12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A12MouseClicked(evt);
            }
        });
        getContentPane().add(A12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 20));

        Ay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_food.png"))); // NOI18N
        Ay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AyMouseClicked(evt);
            }
        });
        getContentPane().add(Ay, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 30, 30));

        Mapa_Superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UIS720.png"))); // NOI18N
        getContentPane().add(Mapa_Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setFont(new java.awt.Font("Roboto", 1, 40)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 720, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Es_Aqui ping_pong = new Es_Aqui();
        ping_pong.setVisible(true);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void P1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MouseClicked
        // TODO add your handling code here:
        /*
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/Imagenes/2.png"));
        
        P1.setIcon(uno);
         */

        G g1 = new G('a');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P1MouseClicked

    private void P2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2MouseClicked
        // TODO add your handling code here:

        G g1 = new G('b');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P2MouseClicked

    private void P3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P3MouseClicked
        // TODO add your handling code here:

        G g1 = new G('c');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P3MouseClicked

    private void P4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P4MouseClicked
        // TODO add your handling code here:

        G g1 = new G('d');

        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_P4MouseClicked

    private void P5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P5MouseClicked
        // TODO add your handling code here:

        G g1 = new G('e');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P5MouseClicked

    private void P6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P6MouseClicked
        // TODO add your handling code here:

        G g1 = new G('f');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P6MouseClicked

    private void P7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P7MouseClicked
        // TODO add your handling code here:

        G g1 = new G('g');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P7MouseClicked

    private void P8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P8MouseClicked
        // TODO add your handling code here:

        G g1 = new G('h');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P8MouseClicked

    private void P9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P9MouseClicked
        // TODO add your handling code here:

        G g1 = new G('i');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P9MouseClicked

    private void P10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P10MouseClicked
        // TODO add your handling code here:

        G g1 = new G('j');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P10MouseClicked

    private void P11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P11MouseClicked
        // TODO add your handling code here:

        G g1 = new G('k');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P11MouseClicked

    private void P12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P12MouseClicked
        // TODO add your handling code here:

        G g1 = new G('l');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P12MouseClicked

    private void P13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P13MouseClicked
        // TODO add your handling code here:

        G g1 = new G('m');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P13MouseClicked

    private void P14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P14MouseClicked
        // TODO add your handling code here:

        G g1 = new G('n');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P14MouseClicked

    private void P15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P15MouseClicked
        // TODO add your handling code here:

        G g1 = new G('o');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P15MouseClicked

    private void P16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P16MouseClicked
        // TODO add your handling code here:

        G g1 = new G('p');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P16MouseClicked

    private void P17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P17MouseClicked
        // TODO add your handling code here:

        G g1 = new G('q');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P17MouseClicked

    private void P18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P18MouseClicked
        // TODO add your handling code here:

        G g1 = new G('r');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P18MouseClicked

    private void P19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P19MouseClicked
        // TODO add your handling code here:

        G g1 = new G('s');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P19MouseClicked

    private void P20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P20MouseClicked
        // TODO add your handling code here:

        G g1 = new G('t');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P20MouseClicked

    private void P21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P21MouseClicked
        // TODO add your handling code here:

        G g1 = new G('u');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P21MouseClicked

    private void P22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P22MouseClicked
        // TODO add your handling code here:

        G g1 = new G('v');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P22MouseClicked

    private void B26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B26MouseClicked
        // TODO add your handling code here:
        Es_Aqui ping_pong = new Es_Aqui();
        ping_pong.setVisible(true);
    }//GEN-LAST:event_B26MouseClicked

    private void P23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P23MouseClicked
        // TODO add your handling code here:G g1 = new G("P22");
        G g1 = new G('w');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P23MouseClicked

    private void P24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P24MouseClicked
        // TODO add your handling code here:G g1 = new G("P22");
        G g1 = new G('x');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P24MouseClicked

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        // TODO add your handling code here:G g1 = new G();
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        // TODO add your handling code here:

        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B6MouseClicked

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B7MouseClicked

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B8MouseClicked

    private void B9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B9MouseClicked

    private void B10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B10MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B10MouseClicked

    private void B11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B11MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B11MouseClicked

    private void B12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B12MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B12MouseClicked

    private void B13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B13MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B13MouseClicked

    private void B14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B14MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B14MouseClicked

    private void B15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B15MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B15MouseClicked

    private void B16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B16MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B16MouseClicked

    private void B17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B17MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B17MouseClicked

    private void B18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B18MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B18MouseClicked

    private void B19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B19MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B19MouseClicked

    private void B20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B20MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B20MouseClicked

    private void B21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B21MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B21MouseClicked

    private void B22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B22MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B22MouseClicked

    private void B23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B23MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B23MouseClicked

    private void B24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B24MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B24MouseClicked

    private void B25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B25MouseClicked
        // TODO add your handling code here:
        B g1 = new B();
        g1.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_B25MouseClicked

    private void E1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E1MouseClicked
        // TODO add your handling code here:

        E g1 = new E('a');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_E1MouseClicked

    private void E2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2MouseClicked
        // TODO add your handling code here:
        E g1 = new E('b');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_E2MouseClicked

    private void E3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E3MouseClicked
        // TODO add your handling code here:
        E g1 = new E('c');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_E3MouseClicked

    private void E4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E4MouseClicked
        // TODO add your handling code here:
        E g1 = new E('d');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_E4MouseClicked

    private void E5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E5MouseClicked
        // TODO add your handling code here:
        E g1 = new E('e');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_E5MouseClicked

    private void EyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EyMouseClicked
        Es_Aqui ping_pong = new Es_Aqui();
        ping_pong.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_EyMouseClicked

    private void TyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TyMouseClicked
        // TODO add your handling code here:
        Es_Aqui ping_pong = new Es_Aqui();
        ping_pong.setVisible(true);
    }//GEN-LAST:event_TyMouseClicked

    private void T1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T1MouseClicked
        // TODO add your handling code here:
          T g1 = new T('a');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_T1MouseClicked

    private void T2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T2MouseClicked
        // TODO add your handling code here:
          T g1 = new T('b');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_T2MouseClicked

    private void T3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3MouseClicked
        // TODO add your handling code here:
          T g1 = new T('c');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_T3MouseClicked

    private void T4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4MouseClicked
        // TODO add your handling code here:
          T g1 = new T('d');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_T4MouseClicked

    private void T5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5MouseClicked
        // TODO add your handling code here:
        T g1 = new T('e');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_T5MouseClicked

    private void T6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T6MouseClicked
        // TODO add your handling code here:
          T g1 = new T('f');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_T6MouseClicked

    private void T7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T7MouseClicked
        // TODO add your handling code here:
          T g1 = new T('g');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_T7MouseClicked

    private void T8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T8MouseClicked
        // TODO add your handling code here:
          T g1 = new T('h');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_T8MouseClicked

    private void HyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HyMouseClicked
        // TODO add your handling code here:
        Es_Aqui ping_pong = new Es_Aqui();
        ping_pong.setVisible(true);
    }//GEN-LAST:event_HyMouseClicked

    private void H1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H1MouseClicked
        // TODO add your handling code here:
        H g1 = new H('a');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_H1MouseClicked

    private void H2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H2MouseClicked
        // TODO add your handling code here:
        H g1 = new H('b');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_H2MouseClicked

    private void H3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H3MouseClicked
        // TODO add your handling code here:
        H g1 = new H('c');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_H3MouseClicked

    private void H4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H4MouseClicked
        // TODO add your handling code here:
        
        H g1 = new H('d');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_H4MouseClicked

    private void H5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H5MouseClicked
        // TODO add your handling code here:
        H g1 = new H('e');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_H5MouseClicked

    private void H6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H6MouseClicked
        // TODO add your handling code here:
        H g1 = new H('f');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_H6MouseClicked

    private void H7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H7MouseClicked
        // TODO add your handling code here:
        H g1 = new H('g');
        g1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_H7MouseClicked

    private void C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseClicked
        // TODO add your handling code here:
         C g1 = new C('a');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_C1MouseClicked

    private void C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseClicked
        // TODO add your handling code here:
         C g1 = new C('b');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_C2MouseClicked

    private void C3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MouseClicked
        // TODO add your handling code here:
         C g1 = new C('c');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_C3MouseClicked

    private void C4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C4MouseClicked
        // TODO add your handling code here:
         C g1 = new C('d');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_C4MouseClicked

    private void C5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C5MouseClicked
        // TODO add your handling code here:
         C g1 = new C('e');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_C5MouseClicked

    private void C6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C6MouseClicked
        // TODO add your handling code here:
         C g1 = new C('f');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_C6MouseClicked

    private void C7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C7MouseClicked
        // TODO add your handling code here:
         C g1 = new C('g');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_C7MouseClicked

    private void C8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C8MouseClicked
        // TODO add your handling code here:
         C g1 = new C('h');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_C8MouseClicked

    private void C9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C9MouseClicked
        // TODO add your handling code here:
         C g1 = new C('i');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_C9MouseClicked

    private void CyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CyMouseClicked
        // TODO add your handling code here:
        Es_Aqui ping_pong = new Es_Aqui();
        ping_pong.setVisible(true);
    }//GEN-LAST:event_CyMouseClicked

    private void D1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1MouseClicked
        // TODO add your handling code here:
         D g1 = new D('a');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D1MouseClicked

    private void D2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2MouseClicked
        // TODO add your handling code here:
         D g1 = new D('b');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D2MouseClicked

    private void D3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D3MouseClicked
        // TODO add your handling code here:
         D g1 = new D('c');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D3MouseClicked

    private void D4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D4MouseClicked
        // TODO add your handling code here:
         D g1 = new D('d');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D4MouseClicked

    private void D5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D5MouseClicked
        // TODO add your handling code here:
         D g1 = new D('e');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D5MouseClicked

    private void D6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D6MouseClicked
        // TODO add your handling code here:
         D g1 = new D('f');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D6MouseClicked

    private void D7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D7MouseClicked
        // TODO add your handling code here:
         D g1 = new D('g');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D7MouseClicked

    private void D8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D8MouseClicked
        // TODO add your handling code here:
         D g1 = new D('h');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D8MouseClicked

    private void D9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D9MouseClicked
        // TODO add your handling code here:
         D g1 = new D('i');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D9MouseClicked

    private void D10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D10MouseClicked
        // TODO add your handling code here:
         D g1 = new D('j');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D10MouseClicked

    private void D11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D11MouseClicked
        // TODO add your handling code here:
         D g1 = new D('k');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D11MouseClicked

    private void D12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D12MouseClicked
        // TODO add your handling code here:
         D g1 = new D('l');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D12MouseClicked

    private void D13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D13MouseClicked
        // TODO add your handling code here:
         D g1 = new D('m');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D13MouseClicked

    private void D14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D14MouseClicked
        // TODO add your handling code here:
         D g1 = new D('n');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D14MouseClicked

    private void D15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D15MouseClicked
        // TODO add your handling code here:
         D g1 = new D('o');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D15MouseClicked

    private void D16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D16MouseClicked
        // TODO add your handling code here:
         D g1 = new D('p');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D16MouseClicked

    private void D17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D17MouseClicked
        // TODO add your handling code here:
         D g1 = new D('q');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D17MouseClicked

    private void D18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D18MouseClicked
        // TODO add your handling code here:
         D g1 = new D('r');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D18MouseClicked

    private void D19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D19MouseClicked
        // TODO add your handling code here:
         D g1 = new D('s');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D19MouseClicked

    private void D20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D20MouseClicked
        // TODO add your handling code here:
         D g1 = new D('t');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D20MouseClicked

    private void D21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D21MouseClicked
        // TODO add your handling code here:
         D g1 = new D('u');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D21MouseClicked

    private void D22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D22MouseClicked
        // TODO add your handling code here:
         D g1 = new D('v');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_D22MouseClicked

    private void DyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DyMouseClicked
        // TODO add your handling code here:
        Es_Aqui ping_pong = new Es_Aqui();
        ping_pong.setVisible(true);
    }//GEN-LAST:event_DyMouseClicked

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        // TODO add your handling code here:
         A g1 = new A('a');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A1MouseClicked

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked
        // TODO add your handling code here:
         A g1 = new A('b');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A2MouseClicked

    private void A3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseClicked
        // TODO add your handling code here:
         A g1 = new A('c');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A3MouseClicked

    private void A4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseClicked
        // TODO add your handling code here:
         A g1 = new A('d');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A4MouseClicked

    private void A5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A5MouseClicked
        // TODO add your handling code here:
         A g1 = new A('e');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A5MouseClicked

    private void A6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A6MouseClicked
        // TODO add your handling code here:
         A g1 = new A('f');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A6MouseClicked

    private void A7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A7MouseClicked
        // TODO add your handling code here:
         A g1 = new A('g');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A7MouseClicked

    private void A8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A8MouseClicked
        // TODO add your handling code here:
         A g1 = new A('h');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A8MouseClicked

    private void A9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A9MouseClicked
        // TODO add your handling code here:
         A g1 = new A('i');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A9MouseClicked

    private void A10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A10MouseClicked
        // TODO add your handling code here:
         A g1 = new A('j');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A10MouseClicked

    private void A11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A11MouseClicked
        // TODO add your handling code here:
         A g1 = new A('k');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A11MouseClicked

    private void A12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A12MouseClicked
        // TODO add your handling code here:
         A g1 = new A('l');
        g1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_A12MouseClicked

    private void AyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyMouseClicked
        // TODO add your handling code here:
        Es_Aqui ping_pong = new Es_Aqui();
        ping_pong.setVisible(true);
    }//GEN-LAST:event_AyMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Voronoi v1 = new Voronoi();
        v1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A10;
    private javax.swing.JLabel A11;
    private javax.swing.JLabel A12;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel A9;
    private javax.swing.JLabel Ay;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B10;
    private javax.swing.JLabel B11;
    private javax.swing.JLabel B12;
    private javax.swing.JLabel B13;
    private javax.swing.JLabel B14;
    private javax.swing.JLabel B15;
    private javax.swing.JLabel B16;
    private javax.swing.JLabel B17;
    private javax.swing.JLabel B18;
    private javax.swing.JLabel B19;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B20;
    private javax.swing.JLabel B21;
    private javax.swing.JLabel B22;
    private javax.swing.JLabel B23;
    private javax.swing.JLabel B24;
    private javax.swing.JLabel B25;
    private javax.swing.JLabel B26;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JLabel B9;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel C9;
    private javax.swing.JLabel Cy;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D10;
    private javax.swing.JLabel D11;
    private javax.swing.JLabel D12;
    private javax.swing.JLabel D13;
    private javax.swing.JLabel D14;
    private javax.swing.JLabel D15;
    private javax.swing.JLabel D16;
    private javax.swing.JLabel D17;
    private javax.swing.JLabel D18;
    private javax.swing.JLabel D19;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D20;
    private javax.swing.JLabel D21;
    private javax.swing.JLabel D22;
    private javax.swing.JLabel D3;
    private javax.swing.JLabel D4;
    private javax.swing.JLabel D5;
    private javax.swing.JLabel D6;
    private javax.swing.JLabel D7;
    private javax.swing.JLabel D8;
    private javax.swing.JLabel D9;
    private javax.swing.JLabel Dy;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E2;
    private javax.swing.JLabel E3;
    private javax.swing.JLabel E4;
    private javax.swing.JLabel E5;
    private javax.swing.JLabel Ey;
    private javax.swing.JLabel H1;
    private javax.swing.JLabel H2;
    private javax.swing.JLabel H3;
    private javax.swing.JLabel H4;
    private javax.swing.JLabel H5;
    private javax.swing.JLabel H6;
    private javax.swing.JLabel H7;
    private javax.swing.JLabel Hy;
    private javax.swing.JLabel Mapa_Superior;
    public javax.swing.JLabel P1;
    private javax.swing.JLabel P10;
    private javax.swing.JLabel P11;
    private javax.swing.JLabel P12;
    private javax.swing.JLabel P13;
    private javax.swing.JLabel P14;
    private javax.swing.JLabel P15;
    private javax.swing.JLabel P16;
    private javax.swing.JLabel P17;
    private javax.swing.JLabel P18;
    private javax.swing.JLabel P19;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P20;
    private javax.swing.JLabel P21;
    private javax.swing.JLabel P22;
    private javax.swing.JLabel P23;
    private javax.swing.JLabel P24;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel P4;
    private javax.swing.JLabel P5;
    private javax.swing.JLabel P6;
    private javax.swing.JLabel P7;
    private javax.swing.JLabel P8;
    private javax.swing.JLabel P9;
    private javax.swing.JLabel T1;
    private javax.swing.JLabel T2;
    private javax.swing.JLabel T3;
    private javax.swing.JLabel T4;
    private javax.swing.JLabel T5;
    private javax.swing.JLabel T6;
    private javax.swing.JLabel T7;
    private javax.swing.JLabel T8;
    private javax.swing.JLabel Ty;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
